### ISSUE TITLE
lockEval为什么锁定的时候不成对？

### ISSUE THREAD

**Issue by starwing** [EmmyLua/EmmyLuaDebugger#29]
你好，

最近在学习emmy_core的源代码，看到下面的行：
https://github.com/EmmyLua/EmmyLuaDebugger/blob/c37ede5580c7b5654feb735c73659ba99bf9d792/emmy_core/emmy_debugger.cpp#L729

请问为什么这里的unlock没有对应的lock？这样会出问题吗？

**Comment by CppCXY** [comment]
2年过去了，这个问题还需要回答吗

**Comment by CppCXY** [comment]
没有回答先关闭了
