### ISSUE TITLE
attempt to index local 'dbg' (a boolean value)

### ISSUE THREAD

**Issue by emelrad12** [EmmyLua/EmmyLuaDebugger#31]
Tried using the new debugger copied the code, and seems that require('emmy_core') results in true and not an object.

```
package.cpath = package.cpath .. ';C:/Users/emelrad12/AppData/Roaming/JetBrains/IntelliJIdea2020.3/plugins/intellij-emmylua/classes/debugger/emmy/windows/x64/?.dll'
local dbg = require('emmy_core')
dbg.tcpConnect('localhost', 9966) --Here error
```

**Comment by CppCXY** [comment]
> Tried using the new debugger copied the code, and seems that require('emmy_core') results in true and not an object.
> 
> ```
> package.cpath = package.cpath .. ';C:/Users/emelrad12/AppData/Roaming/JetBrains/IntelliJIdea2020.3/plugins/intellij-emmylua/classes/debugger/emmy/windows/x64/?.dll'
> local dbg = require('emmy_core')
> dbg.tcpConnect('localhost', 9966) --Here error
> ```

Lua must be compiled as DLL link to exe
