### ISSUE TITLE
在两次pcall调用后的代码step over变为step into

### ISSUE THREAD

**Issue by ximouzhao** [EmmyLua/EmmyLuaDebugger#39]
我们写如下这样一个函数，使用两层pcall调用：
```Lua
function test1()
    local a = 1
    local b = 2
end

function test2()
    local x = 1;
    test1()
    local y = 2
end

function test3()
    pcall(test2)
end

pcall(test3)
```
断点打在`test2()`函数中，在使用step over功能时，会进入到`test0`函数
之所以发现这个问题是因为我们使用 [Lua Busted](https://lunarmodules.github.io/busted/)作为单元测试的工具，但是在调试测试用例的时候无法进行单步调试。

Lua版本：
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio
操作系统：
13.0.1 (22A400) M1 arm
Emmy版本
[EMMY] version: 1.4.1

**Comment by CppCXY** [comment]
明天验证一下
