### ISSUE TITLE
luajit加载emmy_core问题

### ISSUE THREAD

**Issue by DualMoonBird** [EmmyLua/EmmyLuaDebugger#45]
想问一下require(emmy_core)返回true，并没有注册函数，这会是什么原因导致的呢。是编译luajit需要一些特别的设置吗

**Comment by CppCXY** [comment]
动态连接luajit.dll

**Comment by Dyswan** [comment]
我这边也踩过这个坑，主要原因是使用luajit自带的./msvcbat编译出来的lua51.lib是本质上是个动态链接，链接了lua51.dll。因此解决方法有两个
一个是动态链接lua51.dll，
另一个则是将lua51.lib和lua51.dll编译在一起，变成一个硬链接，单这个方法需要将cmake中的add_definitions(-DEMMY_LUA_JIT_SUPPORT_LUA_SETFUNCS) 这一行给取消注释(因为luaL_setFuncs已经被定义)。

**Comment by CppCXY** [comment]
并不是, emmylua调试原生luajit根本不需要重新编译emmy_core. emmylua调试器会检测并加载进程内的lua符号然后判断当前所在的lua环境. 如果进程本身没有导出lua符号则加载lua符号失败会出现issue所表现的问题.  所以解决问题的方案就是导出lua符号, 最简单的就是编译成luajit动态库然后链接编译

**Comment by Dyswan** [comment]
确实原生luajit不需要重新编译，我这边是使用定制化修改过头文件的luajit的修改方式
