### ISSUE TITLE
Debuger does not stop on specific breakpoint

### ISSUE THREAD

**Issue by shubenkovva** [EmmyLua/EmmyLuaDebugger#5]
Hello.

I try to use debug in InlelliJIdea. Looks like it works, but with some issues, if i set the breakpoint on the specific line and start local Debug, the debuger engine starts from the first code line.

Follow I try to use remote debug for nginx. InlelliJIdea says that session connected, but does not stop on breakpoint.

I think that the source of problem is the question - why debuger does not go to the specific breakpoint directly? I tried different versions of InlelliJIdea 2018 and 2019. The same behavior.

**Comment by tangzx** [comment]
If the breakpoint does not work, the main reason is **the lua file path sent to `mobdebug` by IDEA and the path found in `lua debug info` do not match** 
So remote debugger depends on correct `source root` settings.

But, I recommend you to use the new debugger: `Emmy Debugger(New)`
![image](https://user-images.githubusercontent.com/3354360/63747393-9f71bb00-c8d9-11e9-95d0-ab6871c96b35.png)

Install the latest version (`1.3.0.99-IDEA182`) from [JetBrains Plugin](https://plugins.jetbrains.com/plugin/9768-emmylua/versions) to use it  : )
