### ISSUE TITLE
nullptr crash in ejoy2d lua debug

### ISSUE THREAD

**Issue by ljgdsq** [EmmyLua/EmmyLuaDebugger#63]
ejoy2d lua调试。不论使用vscode插件调试还是idea插件调试都是直接crash。好像ejoy2d使用的是32位的lua，不知道是不是这个原因。ejoy2d 我用的是github最新的那个，os是win10 64.

**Comment by CppCXY** [comment]
看起来是几年前的引擎了, 可能你需要自己编译debug版本来调试了, emmylua调试器是支持32位的, 可能lua版本也不对, 你需要找对应的lua版本源码放到调试器的third目录,覆盖对应的lua目录
