### ISSUE TITLE
watch窗口不能展开一个table

### ISSUE THREAD

**Issue by heanrum** [EmmyLua/EmmyLuaDebugger#64]
![image](https://github.com/EmmyLua/EmmyLuaDebugger/assets/12297711/07c5e9e1-7145-47ef-895c-52c82231b1cc)
我在尝试用这个插件调试其它的lua虚拟机的代码，但是发现watch窗口不能展开一个table查看table里面的内容，但是table的size以及直接用index查看table内部的值都是正常的，想问下这个可能是什么原因。

**Comment by CppCXY** [comment]
不知道, 正常的插件是可以展开的
