### ISSUE TITLE
connect ECONNREFUSED 

### ISSUE THREAD

**Issue by phansonloc1999** [EmmyLua/EmmyLuaDebugger#7]
I'm currently using EmmyLua for vscode on Windows and came across this error with new debugger. I have already disabled firewall.

![image](https://user-images.githubusercontent.com/31174158/65410042-8a724400-de13-11e9-8886-5ce06f8432fd.png)

**Comment by tangzx** [comment]
Usage:
1. Open the entry lua file of your app.
2. `shift`+`ctrl`+`p` open command palette, input `Insert Emmy Debugger Code`, then insert code like this
```lua
package.cpath = package.cpath .. ";PATH_TO_EMMY_CORE"
local dbg = require("emmy_core")
dbg.tcpListen("localhost", 9966)
```
3. launch app
4. `F5` launch debugger
