### ISSUE TITLE
IntelliJ debug inside docker container: no breakpoint hit past version 1.7.1

### ISSUE THREAD

**Issue by euri10** [EmmyLua/EmmyLuaDebugger#72]
greetings,

I successfully debug my lua scripts for openresty inside a docker container:
![20241205_0934_1068x933_1733387696](https://github.com/user-attachments/assets/7f4b37ce-b755-4912-9651-66bae73d6578)

I made a repro here: https://github.com/euri10/debuglua

However it stops working anytime I change the [EmmyLuaDebugger](https://github.com/EmmyLua/EmmyLuaDebugger) version in the Dockerfile, everything else stays the same.

Repro instructions:
1. git clone the repo
2. docker compose -f docker-compose.yml up --build --watch
3. Hit http://localhost:9999 in a browser
4. Start IntelliJ, EmmyLua IDE connect debugger

1.7.1: ok
1.8.0 errors:
```
debug_nginx-1  | 172.21.0.1 - - [05/Dec/2024:08:37:01 +0000] "GET / HTTP/1.1" 500 585 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
debug_nginx-1  | 2024/12/05 08:37:01 [error] 7#7: *1 lua entry thread aborted: runtime error: [Emmy]Invalid host. IPv6 error: invalid argument. IPv4 error: invalid argument
debug_nginx-1  | stack traceback:
debug_nginx-1  | coroutine 0:
debug_nginx-1  |        [C]: in function 'tcpListen'
debug_nginx-1  |        /etc/nginx/lua/mylua.lua:16: in main chunk, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:9999"
```
1.8.1 same error:
```
Attaching to debug_nginx-1
debug_nginx-1  | 172.21.0.1 - - [05/Dec/2024:08:37:46 +0000] "GET / HTTP/1.1" 500 585 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
debug_nginx-1  | 2024/12/05 08:37:46 [error] 7#7: *1 lua entry thread aborted: runtime error: [Emmy]Invalid host. IPv6 error: invalid argument. IPv4 error: invalid argument
debug_nginx-1  | stack traceback:
debug_nginx-1  | coroutine 0:
debug_nginx-1  |        [C]: in function 'tcpListen'
debug_nginx-1  |        /etc/nginx/lua/mylua.lua:16: in main chunk, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:9999"
```
1.8.2: no error in logs, just hangs forever
1.8.3: no error in logs, just hangs forever

**Comment by CppCXY** [comment]
EmmyLua debugger prefers to use IPv6 addresses, and when listening on localhost, it is actually listening on the IPv6 address ::1.

This change is due to VSCode's network connection prioritizing IPv6 addresses, while IntelliJ EmmyLua has barely been updated. EmmyLua2 will use IPv6 addresses.

**Comment by euri10** [comment]
thanks for the explanation @CppCXY 

It led me to find a (ugly) workaround so I can use latest 1.8.3 :
just need to ` dbg.tcpListen('0.0.0.0', 9966)` instead of `localhost`
